version: '3.5'
services:
  db:
    image: ghusta/postgres-world-db
    networks:
      - sonarnet
    environment:
      - POSTGRES_DATABASE=world-db  
      - POSTGRES_USER=world
      - POSTGRES_PASSWORD=world123
    ports:
      - 5432:5432
    volumes:
      - C:\data
  web:
    build: .
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080:8080
    networks:
      - sonarnet
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=world
      - DATABASE_NAME=world-db
      - DATABASE_PORT=5432
      
networks:
  sonarnet:
    driver: bridge